import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
import os
from typing import List

def send_daily_insight_email(to_emails: List[str], subject: str, insight_title: str, insight_explanation: str, real_life_scenario: str, sources: List[str]):
    """
    Sends the generated AI Insight email to a list of recipients.
    Uses HTML templates for beautiful formatting.
    """
    sender_email = os.getenv("SENDER_EMAIL")
    sender_password = os.getenv("SENDER_APP_PASSWORD")

    if not sender_email or not sender_password:
        print("Email credentials missing in .env")
        return False

    # HTML Email Template Setup
    source_links_html = "".join([f'<li><a href="{src}" style="color:#2563eb;">{src}</a></li>' for src in sources])
    
    html_content = f"""
    <html>
      <body style="font-family: Arial, sans-serif; background-color: #f9fafb; padding: 20px;">
        <div style="max-width: 600px; margin: 0 auto; background-color: #ffffff; border-radius: 8px; overflow: hidden; box-shadow: 0 4px 6px rgba(0,0,0,0.1);">
          
          <!-- Header -->
          <div style="background-color: #1e3a8a; padding: 20px; text-align: center;">
            <h1 style="color: #ffffff; margin: 0; font-size: 24px;">🧠 Daily AI Insights</h1>
            <p style="color: #bfdbfe; margin: 5px 0 0 0; font-size: 14px;">Curated by Ambuj's Agentic AI</p>
          </div>
          
          <!-- Body -->
          <div style="padding: 30px;">
            <h2 style="color: #111827; margin-top: 0; font-size: 22px;">💡 {insight_title}</h2>
            
            <div style="background-color: #f3f4f6; padding: 15px; border-left: 4px solid #3b82f6; border-radius: 4px; margin-bottom: 25px;">
              <h3 style="color: #1d4ed8; margin-top: 0; font-size: 16px;">The Law / Fact:</h3>
              <p style="color: #374151; margin-bottom: 0; line-height: 1.6;">{insight_explanation}</p>
            </div>
            
            <h3 style="color: #111827; font-size: 18px;">🛡️ Real-Life Problem Solving:</h3>
            <p style="color: #4b5563; line-height: 1.6; margin-bottom: 30px;">{real_life_scenario}</p>
            
            <hr style="border: 0; border-top: 1px solid #e5e7eb; margin-bottom: 20px;">
            
            <h4 style="color: #6b7280; font-size: 14px; margin-bottom: 10px;">Sources Verified via Tavily AI:</h4>
            <ul style="color: #6b7280; font-size: 13px; margin-top: 0; padding-left: 20px;">
              {source_links_html}
            </ul>
          </div>
          
          <!-- Disclaimer -->
          <div style="padding: 0 30px 20px 30px;">
            <p style="color: #9ca3af; font-size: 11px; margin: 0; line-height: 1.5; font-style: italic; text-align: justify;">
              <strong>Disclaimer:</strong> This email is automatically generated by an autonomous AI agent for educational and informational purposes. It does not constitute formal legal, financial, or professional advice. While the AI verifies facts via web search, please consult with a certified professional or refer to official government sources before making any decisions.
            </p>
          </div>

          <!-- Footer -->
          <div style="background-color: #f3f4f6; padding: 15px; text-align: center; border-top: 1px solid #e5e7eb;">
            <p style="color: #9ca3af; font-size: 12px; margin: 0;">
              🤖 Generated autonomously by Agentic ReAct RAG Platform<br>
              Developed by <a href="#" style="color: #2563eb; text-decoration: none;">Ambuj Kumar Tripathi</a> - Gorakhpur, India
            </p>
          </div>
          
        </div>
      </body>
    </html>
    """

    try:
        # Create SMTP session with 30s timeout (prevents infinite hang on Render)
        print("  📧 SMTP: Connecting to smtp.gmail.com:587...")
        server = smtplib.SMTP('smtp.gmail.com', 587, timeout=30)
        
        print("  📧 SMTP: Starting TLS...")
        server.starttls()
        
        print(f"  📧 SMTP: Logging in as {sender_email}...")
        server.login(sender_email, sender_password)
        print("  📧 SMTP: Login successful!")

        # Loop and send (BCC approach or individual)
        for recipient in to_emails:
            msg = MIMEMultipart('alternative')
            msg['Subject'] = subject
            msg['From'] = f"Ambuj's AI Insights <{sender_email}>"
            msg['To'] = recipient

            # Attach HTML content
            part = MIMEText(html_content, 'html')
            msg.attach(part)

            server.send_message(msg)
            print(f"  ✅ SMTP: Sent to {recipient}")

        server.quit()
        print(f"Successfully sent AI Insight to {len(to_emails)} recipients.")
        return True
    except smtplib.SMTPAuthenticationError as e:
        print(f"❌ SMTP AUTH FAILED: {e}. Check SENDER_EMAIL and SENDER_APP_PASSWORD.")
        return False
    except smtplib.SMTPConnectError as e:
        print(f"❌ SMTP CONNECTION FAILED: {e}. Gmail port 587 might be blocked by Render.")
        return False
    except TimeoutError as e:
        print(f"❌ SMTP TIMEOUT: {e}. Connection to Gmail hung for 30+ seconds.")
        return False
    except Exception as e:
        print(f"❌ SMTP UNKNOWN ERROR: {type(e).__name__}: {e}")
        return False
